package com.memobrain.memonow.navegacao

enum class RotasTelas {
    INICIAL,
    LOGIN,
    REGISTRAR,
    HOME,
    INICIO_APP,
    CADERNOS,
    DETALHE_CADERNO,
    EDITAR_CADERNO,
    EDITAR_ARQUIVO,
    CRIAR_CADERNO,
    CRIAR_ARQUIVO,
    CRIAR_PERGUNTA_ABERTA,
    CRIAR_MULTIPLA_ESCOLHA,
    REVISAR_ARQUIVO,
    FLASHCARD_SUMMARY,
}
